%global tl_name luaaddplot
%global tl_revision 72350

Name:		texlive-%{tl_name}
Epoch:		1
Version:	1.0a
Release:	%{tl_revision}.1
Summary:	An extension to pgfplots \addplot macro
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/macros/luatex/generic/luaaddplot
License:	lppl1.3
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/luaaddplot.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/luaaddplot.doc.r%{tl_revision}.tar.xz
Source2:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/luaaddplot.source.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
This package is an extension to pgfplots. It extends the \addplot macro
by a facility which allows modification of data files while they are
read. With luaaddplot it is no longer necessary to pre-process data
files generated by measuring devices with external scripts. This package
can be used with plain LuaTeX or LuaLaTeX.

